---
- hosts: maas
  user: vagrant
  sudo: True
  tasks:
    - name: Install base packages and other usefulness
      action: apt pkg=$item state=installed update_cache=yes
      with_items:
        - language-pack-en-base
    - name: Install maas packages
      shell: DEBIAN_FRONTEND=noninteractive apt-get install -o Dpkg::Options::='--force-confdef' -o Dpkg::Options::='--force-confold' -f -q -y maas maas-dns maas-dhcp </dev/null
    - name: Add maas superuser
      shell: echo "from django.contrib.auth.models import User; User.objects.create_superuser('admin', 'admin@example.com', 'pass')" | sudo maas shell
    - name: Add boot images
      shell: maas-import-pxe-files
