---
- hosts: all
  user: vagrant
  sudo: True
  tasks:
    - name: Install base packages and other usefulness
      action: apt pkg={{item}} state=installed update_cache=yes
      with_items:
        - language-pack-en-base
        - ubuntu-cloud-keyring
        - python-apt
        - python-pycurl
        - maas-enlist
        - maas-cli
    - name: Update system
      apt: upgrade=dist
    - name: enlist node into maas
      command: maas-enlist --serverurl 192.168.50.100 --interface eth1
